### PR TITLE
Logo Submission

### PR DESCRIPTION
**Pull request by ythecombinator**
Hey @Bobeta, congratz on the excellent initiative of creating this project 😄 

I've seen some great work done around the #3 issue - but I was wondering about giving myself a try on it.

There are a few points which I think that could be improved in others proposals - eg. the lack of compliance with _react.js_ visual identity or even the used color palettes, amongst others - and I tried to take those into consideration when making my version.

I thought of a flat - with a minimalist approach - draw involving something that refers to both 
- **functionality** - in this case, things that refer to weather apps/libs; 
- **main technology behind the project** - in this case, the _react.js_ logo. 

I also thought about a flat color scheme, based on a liner gradient that goes from a (very) light shade of red (`#ff6b6b`) to a dark grayish blue one (`#556270`).

In terms of the project name, I chose a flat _sans-serif typeface_ font called Disco, which you can check [here](https://www.fontsquirrel.com/fonts/disco).

The final result goes like:

Logo 

Hope you like it 😃

### CODE REVIEW

**Comment by Bobeta** [comment]
Woow @ythecombinator, I absolutely love it! Thank you so much for this contribution! Really creative! I'm going to merge it in, I was just thinking what do you think about having the text inside the cloud or perhaps to the right of it (so that it gets a more usable shape/ratio)?

**Comment by ythecombinator** [comment]
Sorry for the delay on answering haha 😭

If I got what you mean, a squared ration isn't the right one for the project logo, right?

**Comment by Bobeta** [comment]
I figured it's good as it is 👍 Thanks once again for your amazing contribution! ❤️ could you please send me the source file?

**Comment by ythecombinator** [comment]
I also thank you for the amazing project ❤️ 

Would you prefer me to send via another *PR*, posting a link to the source vector file on this discussion thread - or another way?

**Comment by Bobeta** [comment]
Thanks for the kind words, means a lot ❤️! You can just e-mail it to me to save you the hassle if it's, or post another PR if you like, up to you! 😄 Thanks again!

**Pull request merged**
