### PR TITLE
Here's a suggestion for #3

### PR DESCRIPTION
**Pull request by shin-migami**
react-weather-logo

### CODE REVIEW

**Comment by Bobeta** [comment]
Awesome, very creative! I like your idea! 👍 

**Some suggestions for improvement:**
*Could you perhaps make the globe have some land (green markings) around the react icon? 
*Could you make the cloud more white and in the middle of the react icon so that it doesn't touch the borders? 
*A good idea would be to use flat/material colors for everything (green, blue etc) and have more contrast between the background and the details.

Thanks a lot for your contribution! ❤️

**Comment by shin-migami** [comment]
@Bobeta sure nice suggestions. I'll see what I can cook up

**Comment by Bobeta** [comment]
@shin-migami Awesome, looking forward to see it! 👍

**Comment by Bobeta** [comment]
Feel free to make another PR when you're ready @shin-migami 👍

**Pull request closed without merging**
