### PR TITLE
Icon Proposal

### PR DESCRIPTION
**Pull request by kittyhawks**
Draft one of a secondary icon proposal
reactive

### CODE REVIEW

**Comment by Bobeta** [comment]
Really beautiful and creative, I love it! ❤️  Thanks for this amazing contribution! 👍  Could you add the source without the background as well?

**Comment by kittyhawks** [comment]
I have added the source file along with an image with no background.

**Comment by kittyhawks** [comment]
reactive_clean

**Comment by Bobeta** [comment]
Great! Thank you very much for your contribution @kittyhawks ! Amazing work! ❤️

**Pull request merged**
