### PR TITLE
Issue: CSS / Design improvements - Default Theme

### PR DESCRIPTION
**Pull request by davoscript**
Hello and congratulations for creating this nice project!

This pull request address the issue #2 

This branch adds a default theme CSS file. To achieve this, some simple layout changes where made in the components, including removing some hardcoded styling objects passed to the render method.

In order to use the theme, a single CSS file should be included in the HTML document:

`<link rel="stylesheet" type="text/css" href="css/rw-theme-default.css">`

image

### CODE REVIEW

**Comment by davoscript** [comment]
@Bobeta should I ignore in my branch some files like: weatherservice.js and other generated files?

**Comment by Bobeta** [comment]
Wooww, incredible work @davoscript, it looks absolutely gorgeous! Thank you very much for this amazing contribution! Could you just please remove your personal API and I'll merge the PR? 💓

**Comment by nonintanon** [comment]
This look nice :)

**Comment by davoscript** [comment]
Glad you liked it @Bobeta, I really think your project is a very useful tool and a very didactic way to learn React!

I just pushed the update removing my API KEY ;) I also noted that there's another PR that refactors the code, that one may crash with this one since I modified some components too so be careful ;)

Best!

**Pull request merged**
